name: Release R3SubscribeAnalyzer

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'バージョン番号（例：v1.0.0）'
        required: true
        type: string

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Create branch for PR
        run: |
          git checkout -b update-dll-${{ inputs.version }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0

      - name: Restore dependencies
        run: dotnet restore R3SubscribeAnalyzer.sln

      - name: Build solution
        run: dotnet build R3SubscribeAnalyzer.sln --configuration Release --no-restore

      - name: Copy DLL to Unity package
        run: |
          mkdir -p R3SubscribeAnalyzer/Runtime
          copy R3SubscribeAnalyzer\\bin\\Release\\netstandard2.0\\R3SubscribeAnalyzer.dll R3SubscribeAnalyzer/Runtime/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-dll-${{ inputs.version }}
          title: "Update DLL for ${{ inputs.version }}"
          body: "Automated PR to update DLL from build"
          base: main